{{- if .Values.server.conf.createCustomConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "unity-catalog.fullname" . }}-custom-config
  labels:
    {{- include "unity-catalog.labels" . | nindent 4 }}
  {{- with .Values.server.conf.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
{{- if .Values.server.conf.log4j2 }}
  log4j2server.log4j2.properties: |-
    {{- .Values.server.conf.log4j2 | nindent 4 }}
{{- end }}
{{- if .Values.server.conf.hibernate }}
  hibernate.properties: |-
     {{- .Values.server.conf.hibernate | nindent 4 }}
{{- end }}
{{- if .Values.server.conf.server }}
  server.properties: |-
     {{- .Values.server.conf.server | nindent 4 }}
{{- end }}
{{- end }}