apiVersion: v1
kind: Service
metadata:
  name: {{ include "unity-catalog.fullname" . }}
  labels:
    {{- include "unity-catalog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "unity-catalog.selectorLabels" . | nindent 4 }}
---
{{- if and .Values.server.create (.Values.server.replicas | int | eq 1) }}
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    {{- include "unity-catalog.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/component: server
  sessionAffinity: None
  type: ClusterIP
{{- end }}