{{- if and .Values.server.create ( .Values.server.replicaCount | int | gt 1) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "unity-catalog.fullname" . }}-server
  labels:
    {{- include "unity-catalog.labels" . | nindent 4 }}
spec:
  {{- if not .Values.ui.autoscaling.enabled }}
  replicas: {{ .Values.ui.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "unity-catalog.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.ui.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "unity-catalog.labels" . | nindent 8 }}
        {{- with .Values.ui.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.ui.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "unity-catalog.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.ui.podSecurityContext | nindent 8 }}
      initContainers:
        {{- with .Values.server.initContainers }}
          {{- toYaml . | nindent 12 }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.ui.securityContext | nindent 12 }}
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          env:
          - name: PROXY_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          ports:
            - name: http
              containerPort: {{ .Values.ui.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.ui.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.ui.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
          {{- with .Values.ui.volumeMounts }}
          volumeMounts:
            - name: empty-dir
              mountPath: /tmp
          {{- with .Values.server.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
            {{- if .Values.server.conf.log4j2 }}
            - mountPath: /home/unitycatalog/etc/conf/log4j2server.log4j2.properties
              name: custom-configuration
              subPath: log4j2server.log4j2.properties
            {{- end }}
            {{- if .Values.server.conf.hibernate }}
            - mountPath: /home/unitycatalog/etc/conf/hibernate.properties
              name: custom-configuration
              subPath: hibernate.properties
            {{- end }}
            {{- if .Values.server.conf.server }}
            - mountPath: /home/unitycatalog/etc/conf/server.properties
              name: custom-configuration
              subPath: server.properties
            {{- end }}
      volumes:
        - name: empty-dir
          emptyDir: {}
      {{- with .Values.server.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        {{- if .Values.server.conf.createCustomConfig }}
        - name: custom-configuration
          configMap:
            name: {{ include "unity-catalog.fullname" . }}-custom-config
            items:
            {{- if .Values.server.conf.log4j2 }}
              - key: log4j2server.log4j2.properties
                path: log4j2server.log4j2.properties
            {{- end }}
            {{- if .Values.server.conf.hibernate }}
              - key: hibernate.properties
                path: hibernate.properties
            {{- end }}
            {{- if .Values.server.conf.server }}
              - key: server.properties
                path: server.properties
            {{- end }}
        {{- end }}
      {{- end }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}