{{- if and .Values.server.create (.Values.server.replicaCount | int | eq 1) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "unity-catalog.fullname" . }}-server
  labels:
    app.kubernetes.io/component: server
    {{- include "unity-catalog.labels" . | nindent 4 }}
spec:
  serviceName: server
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      {{- include "unity-catalog.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: server
        {{- include "unity-catalog.labels" . | nindent 8 }}
        {{- with .Values.server.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.server.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "unity-catalog.serviceAccountName" . }}-server
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-server
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.server.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.server.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.server.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          {{- with .Values.server.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
            {{- if .Values.server.conf.log4j2 }}
            - mountPath: /home/unitycatalog/etc/conf/log4j2server.log4j2.properties
              name: custom-configuration
              subPath: log4j2server.log4j2.properties
            {{- end }}
            {{- if .Values.server.conf.hibernate }}
            - mountPath: /home/unitycatalog/etc/conf/hibernate.properties
              name: custom-configuration
              subPath: hibernate.properties
            {{- end }}
            {{- if .Values.server.conf.server }}
            - mountPath: /home/unitycatalog/etc/conf/server.properties
              name: custom-configuration
              subPath: server.properties
            {{- end }}
          {{- end }}
      {{- with .Values.server.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
        {{- if .Values.server.conf.createCustomConfig }}
        - name: custom-configuration
          configMap:
            name: {{ include "unity-catalog.fullname" . }}-custom-config
            items:
            {{- if .Values.server.conf.log4j2 }}
              - key: log4j2server.log4j2.properties
                path: log4j2server.log4j2.properties
            {{- end }}
            {{- if .Values.server.conf.hibernate }}
              - key: hibernate.properties
                path: hibernate.properties
            {{- end }}
            {{- if .Values.server.conf.server }}
              - key: server.properties
                path: server.properties
            {{- end }}
        {{- end }}
      {{- end }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.server.volumeClaimTemplates }}
  volumeClaimTemplates:
    {{- toYaml .Values.server.volumeClaimTemplates | nindent 4 }}
  {{- end }}
{{- end }}
