name: Generate Helm documentation
on:
  - pull_request
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Run helm-docs
      uses: losisin/helm-docs-github-action@8df0bb44b104f5954587199c9a2304f4c4c663fc # v1.3.5
      with:
        template-files: ./README.md.gotmpl
        sort-values-order: file
        git-push: true
